default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: testing_tailwind_development

test:
  <<: *default
  database: testing_tailwind_test

production:
  <<: *default
  database: testing_tailwind_production
  username: testing_tailwind
  password: <%= ENV['TESTING_TAILWIND_DATABASE_PASSWORD'] %>
